server:
  port: ${random.int(8000, 8100)}
  servlet:
    context-path: /sistema-escolar

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sistema_escolar
    username: root
    password: TamiLala#_7
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
eureka:
  client:
    fetch-registry=true: true
    register-with-eureka=true: true
    service-url:
      default-zone=: http://localhost:8761/eureka