server:
  port: ${random.int(8000,8100)}
  servlet:
    context-path: /sistema-academia

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sistema_academia
    username: postgres
    password: TamiLala#_7
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true

eureka:
  client:
    fetch-registry=true: true
    register-with-eureka=true: true
    service-url:
      default-zone=: http://localhost:8761/eureka

