server:
  port: ${PORT:${SERVER_PORT:0}}
  servlet:
    context-path: /coordinacion-academica

spring:
  application:
    name: coordinacion-academica
  datasource:
    url: jdbc:postgresql://localhost:5432/sistema_academia
    username: postgres
    password: TamiLala#_7
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
